# Generated by Django 5.2.4 on 2025-07-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('nrn', models.CharField(blank=True, max_length=255, null=True)),
                ('first_norm', models.CharField(blank=True, max_length=255, null=True)),
                ('last_norm', models.CharField(blank=True, max_length=255, null=True)),
                ('nrn_norm', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
