# Generated by Django 5.2.4 on 2025-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalregister',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
