# Generated by Django 5.2.4 on 2025-07-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_nationalregister_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalregister',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationalregister',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationalregister',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationalregister',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationalregister',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
