# Generated by Django 4.2.23 on 2025-07-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_update_nationalregister_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalregister',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='nationalregister',
            unique_together={('nrn', 'year')},
        ),
    ]
